import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import React from 'react';
import Navbar from '@/components/Navbar/Navbar';
import Intro from '@/components/Intro/Intro';
import About from '@/components/About/About';
import Projects from '@/components/Projects/Projects';
import Contact from '@/components/Contact/Contact';

export default function Home(): JSX.Element {
  const [theme, setTheme] = React.useState('light');

  const changeTheme = (): void => {
    setTheme(theme === 'light' ? 'dark' : 'light');
  };

  React.useEffect(() => {
    document.getElementById('general')?.setAttribute('data-theme', theme);
  }, [theme]);

  return (
    <>
      <Head>
        <title>GusEngers - Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='apple-touch-icon'
          sizes='180x180'
          href='/apple-touch-icon.png'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='32x32'
          href='/favicon-32x32.png'
        />
        <link
          rel='icon'
          type='image/png'
          sizes='16x16'
          href='/favicon-16x16.png'
        />
        <link rel='manifest' href='/site.webmanifest'></link>
      </Head>
      <main id='general' className={styles.main}>
        <div className={styles.container}>
          <Navbar theme={theme} action={changeTheme} />
          <Intro />
          <About />
          <Projects />
          <Contact />
        </div>
      </main>
    </>
  );
}
